[server]
port = 8501
baseUrlPath = "knowledge"
headless = true
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = false
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "gustav1.ux.uis.no"
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "light"

[runner]
magicEnabled = false
fastReruns = false
enforceSerializableSessionState = false

[global]
developmentMode = false